version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      
ports:
  - "5173:5173"
volumes:
  - ./frontend:/app
  - /app/node_modules
depends_on:
  - backend

backend:
  build: ./backend
  volumes:
    - ./backend:/app
  ports:
    - "8000:8000"
command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"